const { chromium } = require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('fs');
const path = require('path');
const spacing={0:'0',px:'1px',0.5:'.125rem',1:'.25rem',1.5:'.375rem',2:'.5rem',2.5:'.625rem',3:'.75rem',3.5:'.875rem',4:'1rem',5:'1.25rem',6:'1.5rem',8:'2rem',10:'2.5rem',12:'3rem',14:'3.5rem',16:'4rem',20:'5rem',24:'6rem',32:'8rem'};
const pal={slate:['#f8fafc','#f1f5f9','#e2e8f0','#cbd5e1','#94a3b8','#64748b','#475569','#334155','#1e293b','#0f172a'],blue:['#eff6ff','#dbeafe','#bfdbfe','#93c5fd','#60a5fa','#3b82f6','#2563eb','#1d4ed8','#1e40af','#1e3a8a'],indigo:['#eef2ff','#e0e7ff','#c7d2fe','#a5b4fc','#818cf8','#6366f1','#4f46e5','#4338ca','#3730a3','#312e81'],emerald:['#ecfdf5','#d1fae5','#a7f3d0','#6ee7b7','#34d399','#10b981','#059669','#047857','#065f46','#064e3b'],rose:['#fff1f2','#ffe4e6','#fecdd3','#fda4af','#fb7185','#f43f5e','#e11d48','#be123c','#9f1239','#881337'],amber:['#fffbeb','#fef3c7','#fde68a','#fcd34d','#fbbf24','#f59e0b','#d97706','#b45309','#92400e','#78350f'],white:['#fff'],black:['#000']};
const shades={'50':0,'100':1,'200':2,'300':3,'400':4,'500':5,'600':6,'700':7,'800':8,'900':9};
function cssFor(cls){let p=[];const add=(prop,val)=>p.push(`${prop}:${val}`);let m;
 if(cls==='flex')add('display','flex'); else if(cls==='grid')add('display','grid');else if(cls==='block')add('display','block');else if(cls==='inline-flex')add('display','inline-flex');else if(cls==='hidden')add('display','none');
 if(cls==='flex-col')add('flex-direction','column');if(cls==='flex-row')add('flex-direction','row');if(cls==='flex-wrap')add('flex-wrap','wrap');if(cls==='flex-grow'||cls==='grow')add('flex-grow','1');if(cls==='shrink-0')add('flex-shrink','0');
 if((m=cls.match(/^justify-(between|center|evenly|start|end)$/)))add('justify-content',({between:'space-between',center:'center',evenly:'space-evenly',start:'flex-start',end:'flex-end'})[m[1]]);
 if((m=cls.match(/^items-(start|end|center|baseline|stretch)$/)))add('align-items',({start:'flex-start',end:'flex-end',center:'center',baseline:'baseline',stretch:'stretch'})[m[1]]);
 if((m=cls.match(/^grid-cols-(\d)$/)))add('grid-template-columns',`repeat(${m[1]},minmax(0,1fr))`);
 if((m=cls.match(/^gap-(.+)$/))&&spacing[m[1]])add('gap',spacing[m[1]]);
 if((m=cls.match(/^(p|px|py|pt|pb|pl|pr|m|mx|my|mt|mb|ml|mr)-(.+)$/))&&spacing[m[2]]){const x=spacing[m[2]],key=m[1];({p:()=>add('padding',x),px:()=>{add('padding-left',x);add('padding-right',x)},py:()=>{add('padding-top',x);add('padding-bottom',x)},pt:()=>add('padding-top',x),pb:()=>add('padding-bottom',x),pl:()=>add('padding-left',x),pr:()=>add('padding-right',x),m:()=>add('margin',x),mx:()=>{add('margin-left',x);add('margin-right',x)},my:()=>{add('margin-top',x);add('margin-bottom',x)},mt:()=>add('margin-top',x),mb:()=>add('margin-bottom',x),ml:()=>add('margin-left',x),mr:()=>add('margin-right',x)})[key]()}
 if((m=cls.match(/^(w|h)-(.+)$/))){let v=spacing[m[2]]||({'full':'100%','screen':'100vw','1/2':'50%','1/3':'33.333333%','2/3':'66.666667%'})[m[2]];if(v)add(m[1]==='w'?'width':'height',v)}
 if((m=cls.match(/^max-w-(.+)$/))){let v=spacing[m[1]]||({'full':'100%','xl':'36rem','2xl':'42rem','\[1060px\]':'1060px'})[m[1]];if(v)add('max-width',v)}
 if((m=cls.match(/^rounded(?:-(.+))?$/)))add('border-radius',({'':'0.25rem','sm':'0.125rem','md':'0.375rem','lg':'0.5rem','xl':'0.75rem','2xl':'1rem','full':'9999px'})[m[1]||'']||'0.5rem');
 if(cls==='border')add('border-width','1px');else if((m=cls.match(/^border-(\d)$/)))add('border-width',m[1]+'px');
 if((m=cls.match(/^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl)$/)))add('font-size',({xs:'.75rem',sm:'.875rem',base:'1rem',lg:'1.125rem',xl:'1.25rem','2xl':'1.5rem','3xl':'1.875rem','4xl':'2.25rem','5xl':'3rem'})[m[1]]);
 if((m=cls.match(/^text-\[(\d+(?:\.\d+)?)(px|rem)\]$/)))add('font-size',m[1]+m[2]);
 if((m=cls.match(/^font-(medium|semibold|bold|extrabold|black|normal)$/)))add('font-weight',({normal:'400',medium:'500',semibold:'600',bold:'700',extrabold:'800',black:'900'})[m[1]]);
 if((m=cls.match(/^text-(left|center|right)$/)))add('text-align',m[1]);if(cls==='uppercase')add('text-transform','uppercase');if(cls==='text-white')add('color','#fff');if(cls==='text-black')add('color','#000');
 if((m=cls.match(/^(text|bg|border)-(slate|blue|indigo|emerald|rose|amber)-(50|100|200|300|400|500|600|700|800|900)$/))){const color=pal[m[2]]?.[shades[m[3]]];if(color)add(({text:'color',bg:'background-color',border:'border-color'})[m[1]],color)}
 if(cls==='bg-white')add('background-color','#fff');if(cls==='bg-black')add('background-color','#000');if(cls.startsWith('bg-gradient-to-'))add('background-image','linear-gradient(to right,#eff6ff,#eef2ff)');
 if((m=cls.match(/^leading-(tight|snug|relaxed|loose|\d+)$/)))add('line-height',({tight:'1.25',snug:'1.375',relaxed:'1.625',loose:'2'})[m[1]]||`${m[1]}px`);
 if(cls==='relative')add('position','relative');if(cls==='absolute')add('position','absolute');if(cls==='overflow-hidden')add('overflow','hidden');if(cls==='overflow-x-auto')add('overflow-x','auto');if(cls==='text-transparent')add('color','transparent');if(cls==='underline')add('text-decoration','underline');if(cls==='tracking-tight')add('letter-spacing','-.025em');if(cls==='tracking-wide')add('letter-spacing','.025em');if(cls==='uppercase')add('text-transform','uppercase');if(cls==='shadow-sm'||cls==='shadow-md'||cls==='shadow-lg'||cls==='shadow-xl')add('box-shadow','0 2px 8px rgba(15,23,42,.12)');
 return p.length?`[class~="${cls.replace(/"/g,'\\"')}"]{${p.join(';')}}`:'';
}
(async()=>{
 const repoRoot=path.resolve(__dirname,'..');const sourcePath=path.join(repoRoot,'src','report.html');const releasePath=path.join(repoRoot,'releases','2026-10','261008_프라이어팰리스 리노베이션 공감리포트_26년 10월_Rev11.pdf');
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:1200,height:850}});
 await page.goto('file:///'+sourcePath.replace(/\\/g,'/'),{waitUntil:'domcontentloaded'});await page.waitForTimeout(500);
 const source=fs.readFileSync(sourcePath,'utf8');const tokens=new Set([...source.matchAll(/class="([^"]+)"/g)].flatMap(m=>m[1].split(/\s+/)));const css=[...tokens].map(cssFor).join('\n');
 const coverUrl=require('url').pathToFileURL(path.join(repoRoot,'assets','1789111849595 (1).png')).href;
 const printCss=`
 @media (min-width:768px){.md\\:grid-cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}.md\\:grid-cols-3{grid-template-columns:repeat(3,minmax(0,1fr))}.md\\:text-3xl{font-size:1.875rem}.md\\:text-2xl{font-size:1.5rem}.md\\:text-sm{font-size:.875rem}.md\\:text-xs{font-size:.75rem}} @media (min-width:1024px){.lg\\:text-5xl{font-size:3rem}}
 @page{size:A4 landscape;margin:0} html,body{margin:0!important;padding:0!important;width:297mm!important;font-family:Arial,'Malgun Gothic',sans-serif!important;color:#0f172a} .no-print{display:none!important}
 .ppt-slide{width:297mm!important;max-width:none!important;height:210mm!important;min-height:0!important;box-sizing:border-box!important;margin:0!important;padding:8mm 10mm!important;border:0!important;border-radius:0!important;box-shadow:none!important;overflow:hidden!important;break-after:page!important;page-break-after:always!important;display:flex!important;flex-direction:column!important;justify-content:space-between!important}.ppt-slide:last-of-type{break-after:auto!important;page-break-after:auto!important}
 .ppt-slide [class~="text-xs"],.ppt-slide [class*="text-[11px]"],.ppt-slide [class*="text-[10px]"]{font-size:14.5px!important;line-height:1.42!important}.ppt-slide [class~="text-sm"]{font-size:16.5px!important;line-height:1.48!important}.ppt-slide [class~="text-base"]{font-size:18px!important}.ppt-slide [class~="text-lg"]{font-size:21px!important}.ppt-slide h2{font-size:42px!important;line-height:1.16!important}.ppt-slide h3{font-size:30px!important;line-height:1.22!important}.ppt-slide h4{font-size:21px!important;line-height:1.3!important}.ppt-slide h5{font-size:18px!important}
 .ppt-slide>div:first-child{flex-shrink:0;min-height:55px}.ppt-slide>div:last-child{font-size:13.5px!important;padding-top:9px!important;margin-top:8px!important;flex-shrink:0}.ppt-slide p{line-height:1.48!important}.ppt-slide table{width:100%;height:100%;border-collapse:collapse}.ppt-slide th,.ppt-slide td{border:1px solid #cbd5e1;padding:10px 12px!important;vertical-align:middle}.ppt-slide th{font-size:16px!important}.ppt-slide td{font-size:15px!important;line-height:1.45!important}
 .ppt-slide[class*="!bg-slate-900"]{background:#0f172a!important}.ppt-slide[class*="!bg-slate-900"]>div:last-child{color:#94a3b8!important;border-color:#334155!important}.ppt-slide[class*="!bg-slate-900"]>div:first-child{border-color:#334155!important}
 .cover-bg{background-image:linear-gradient(rgba(15,23,42,.68),rgba(15,23,42,.78)),url("${coverUrl}")!important;background-size:cover!important;background-position:center!important;background-repeat:no-repeat!important;background-color:#0f172a!important}.cover-bg h2,.cover-bg p,.cover-bg span{color:#fff!important}.cover-bg h2 span{color:#fbbf24!important}
 .ppt-slide:nth-of-type(2) .p2-intro{font-size:17px!important;line-height:1.5!important;margin:10px 0 14px!important;padding:12px 16px!important;border-left:5px solid #2563eb;background:#eff6ff;border-radius:0 12px 12px 0}.ppt-slide:nth-of-type(2) .p2-rules{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px!important;align-items:stretch}.ppt-slide:nth-of-type(2) .p2-rules>div{display:flex!important;flex-direction:column!important;gap:14px!important;padding:21px!important;border-radius:18px!important;min-height:260px!important;box-shadow:0 10px 24px rgba(15,23,42,.08);border-top:5px solid #2563eb!important}.ppt-slide:nth-of-type(2) .p2-rules>div:nth-child(2){border-top-color:#059669!important}.ppt-slide:nth-of-type(2) .p2-rules>div:nth-child(3){border-top-color:#e11d48!important}.ppt-slide:nth-of-type(2) .p2-rules .w-12{width:56px!important;height:56px!important;font-size:17px!important;font-weight:900!important}.ppt-slide:nth-of-type(2) .p2-rules h4{font-size:21px!important;line-height:1.3!important}.ppt-slide:nth-of-type(2) .p2-rules p{font-size:16px!important;line-height:1.55!important}.ppt-slide:nth-of-type(2) .p2-rules a{display:inline-flex!important;margin-top:9px!important;font-size:14px!important;white-space:nowrap}.ppt-slide:nth-of-type(2) .p2-rules>div:first-child .w-full>div:first-child{display:block!important}
 .ppt-slide:nth-of-type(3) .problem-flow{display:grid!important;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:10px!important;margin:12px 0 8px!important}.problem-label{grid-column:1/-1;color:#334155;font-size:16px;font-weight:900;letter-spacing:.03em;margin-bottom:2px}.ppt-slide:nth-of-type(3) .problem-flow>div:nth-child(2),.ppt-slide:nth-of-type(3) .problem-flow>div:nth-child(4),.ppt-slide:nth-of-type(3) .problem-flow>div:nth-child(6){padding:11px!important;border-radius:14px!important;border:1px solid #bfdbfe!important;border-bottom:4px solid #3b82f6!important;background:#fff!important;box-shadow:0 3px 12px #0f172a12}.problem-index{display:inline-flex;width:29px;height:29px;align-items:center;justify-content:center;border-radius:50%;background:#dbeafe;color:#1d4ed8;font-weight:900;font-size:14px;margin-bottom:5px}.problem-flow small{display:block;color:#64748b;font-size:14px;margin-top:4px}.ppt-slide:nth-of-type(3) .flow-plus{font-size:27px!important;color:#2563eb!important}.ppt-slide:nth-of-type(3) .flow-arrow{display:inline-flex;align-items:center;justify-content:center;width:30px;height:30px;border-radius:50%;background:#dbeafe;color:#1d4ed8;font-size:21px;font-weight:900;margin-right:8px}.ppt-slide:nth-of-type(3) .problem-summary{padding:10px!important;font-size:16px!important;background:#eff6ff!important;border-radius:13px!important;margin:5px 0 10px!important}
 .ppt-slide:nth-of-type(3)>div:nth-child(4){padding:10px!important;margin:0 0 6px!important;border-radius:16px!important;min-height:0!important;flex-shrink:0!important;display:flex!important;align-items:center!important;gap:12px!important}.ppt-slide:nth-of-type(3)>div:nth-child(4) .priority-copy{flex:1;min-width:0}.ppt-slide:nth-of-type(3)>div:nth-child(4) h4{font-size:19px!important;line-height:1.2!important}.ppt-slide:nth-of-type(3)>div:nth-child(4) p{font-size:14.5px!important;line-height:1.35!important;margin-top:3px!important}.priority-visual{width:195px;flex:0 0 195px;display:grid;grid-template-columns:1fr 1fr;gap:3px;align-items:center}.concept-photo{grid-column:1/-1;width:100%;height:43px;object-fit:cover;object-position:center 60%;border-radius:7px;border:1px solid #64748b}.concept-caption{grid-column:1/-1;color:#cbd5e1;font-size:9px;line-height:1.05;text-align:center}.hillstate-lockup{grid-column:1/-1;background:#fff;border-radius:7px;padding:2px 6px;display:flex;align-items:center;justify-content:center;gap:6px}.hillstate-lockup img{width:110px;height:25px;object-fit:contain}.hillstate-lockup span{font-size:9px;color:#64748b;white-space:nowrap}.ppt-slide:nth-of-type(3)>div:nth-child(5){display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px!important;min-height:0!important}.ppt-slide:nth-of-type(3)>div:nth-child(5)>div{padding:10px!important;border-radius:14px!important;min-height:0!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) h5{font-size:16.5px!important;margin-bottom:4px!important}.ppt-slide:nth-of-type(3) .w-10{width:34px!important;height:34px!important;font-size:15px!important;font-weight:900!important;margin-bottom:7px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) p{font-size:14px!important;line-height:1.34!important;margin-bottom:5px!important;flex-grow:0!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) .text-\[11px\]{font-size:13px!important;padding-top:6px!important}
 .ppt-slide:nth-of-type(6)>div:nth-child(2)>div:first-child{padding:22px!important}
 .ppt-slide:nth-of-type(7) table th,.ppt-slide:nth-of-type(7) table td{padding:13px 12px!important;font-size:15px!important}.ppt-slide:nth-of-type(7)>div:nth-child(2){margin:14px 0!important}.ppt-slide:nth-of-type(7)>div:nth-child(3){padding:16px!important;font-size:15px!important}.ppt-slide:nth-of-type(7) .law-source{font-size:12px!important;margin:4px 0 0!important;text-align:right}.law-source a,.jamsil-case a{color:#2563eb;text-decoration:underline;font-size:12px!important}
 .slide-roadmap .roadmap-list{border-left:0!important;padding-left:0!important;gap:5px!important;justify-content:space-between!important}.slide-roadmap>div:nth-child(2){margin:8px 0!important}.roadmap-step{display:flex!important;align-items:center;gap:12px!important;padding:6px 10px!important;margin:2px 0!important;border:1px solid #e2e8f0;border-radius:12px;background:#f8fafc;min-height:43px}.roadmap-step.is-current{border-color:#a7f3d0;background:#ecfdf5}.roadmap-step.is-target{border-color:#93c5fd;background:#eff6ff}.roadmap-number{display:flex;flex:0 0 32px;width:32px;height:32px;align-items:center;justify-content:center;border-radius:50%;background:#e2e8f0;color:#334155;font-size:14px;font-weight:900}.roadmap-step.is-current .roadmap-number{background:#059669;color:white}.roadmap-step.is-target .roadmap-number{background:#2563eb;color:white}
 .slide-case .jamsil-case-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:2px 0 6px}.slide-case .jamsil-case{padding:9px 11px;border-radius:12px;border:1px solid #475569;background:#1e293b;color:#e2e8f0}.slide-case .jamsil-case strong{display:block;color:#fff;font-size:15px;margin-bottom:3px}.slide-case .jamsil-case p{font-size:13.5px!important;line-height:1.3!important;margin:0 0 4px}.slide-case .jamsil-case a{color:#bfdbfe!important;font-size:11px!important}.slide-case .case-timeline{display:flex;gap:8px;align-items:center;font-size:12px;color:#cbd5e1;margin:1px 0 3px}.slide-case .case-timeline b{color:#fbbf24}.strategy-copy{font-size:13.5px!important;line-height:1.3!important}.slide-case>div:nth-child(2){margin-top:5px!important;margin-bottom:5px!important}.slide-case .bg-slate-50{padding:8px!important}.slide-case>div:nth-child(4){padding:9px!important;margin-top:1px!important}.slide-case>div:nth-child(4) p{font-size:13.5px!important;line-height:1.3!important}.slide-case>div:nth-child(2)>div{padding:8px!important}.slide-case>div:nth-child(2) p{font-size:13px!important;line-height:1.28!important}.slide-case>div:nth-child(2) .bg-slate-50{padding:6px!important}.slide-case>div:nth-child(2) .space-y-3{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px!important}.slide-case>div:nth-child(2) .space-y-3>div{padding:7px!important}.slide-case>div:nth-child(2) .space-y-3 strong{font-size:13px!important;line-height:1.2!important}.slide-case>div:nth-child(2) .space-y-3 span{font-size:12.5px!important;line-height:1.25!important}
 .ppt-slide:nth-of-type(10) table td{font-size:15px!important;padding:11px 14px!important}.ppt-slide:nth-of-type(10) table th{font-size:16px!important;padding:12px!important}
 .ppt-slide:nth-of-type(3)>div:nth-child(5){flex:0 0 182px!important;height:182px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5)>div{padding:9px!important;overflow:hidden!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) h5{font-size:16px!important;margin-bottom:3px!important}.ppt-slide:nth-of-type(3) .w-10{width:31px!important;height:31px!important;font-size:14px!important;margin-bottom:5px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) p{font-size:13.8px!important;line-height:1.25!important;margin-bottom:3px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) .text-\\[11px\\]{font-size:12.5px!important;padding-top:4px!important}.ppt-slide:nth-of-type(10)>div:first-child>div:first-child{max-width:86%!important}.ppt-slide:nth-of-type(10)>div:first-child h3{font-size:27px!important;line-height:1.2!important}
 .concept-photo{height:50px!important;object-position:center 48%!important}.concept-caption{font-size:9.5px!important;line-height:1.1!important}
 .ppt-slide:nth-of-type(4){background:linear-gradient(135deg,#f8fbff 0%,#ffffff 58%,#f2f8ff 100%)!important}.ppt-slide:nth-of-type(4)>div:first-child{min-height:62px!important}.ppt-slide:nth-of-type(4) .sep-participation{display:grid!important;grid-template-columns:auto 1fr!important;column-gap:14px!important;align-items:center!important;margin:12px 0 10px!important;padding:11px 15px!important;border:1px solid #bfdbfe!important;border-left:6px solid #2563eb!important;border-radius:14px!important;background:#eff6ff!important}.sep-kicker{grid-row:span 2;display:flex!important;align-items:center;justify-content:center;width:86px;height:42px;border-radius:9px;background:#1d4ed8;color:white;font-size:14px;font-weight:900;text-align:center}.sep-participation strong{font-size:18px;color:#0f172a}.sep-participation span:last-child{font-size:15px;color:#475569;margin-top:2px}.ppt-slide:nth-of-type(4) .sep-grid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:13px!important;align-items:stretch!important;margin:0 0 9px!important}.ppt-slide:nth-of-type(4) .sep-card{display:flex!important;gap:11px!important;padding:16px!important;border-radius:16px!important;background:#fff!important;border:1px solid #dbeafe!important;border-top:5px solid #2563eb!important;box-shadow:0 5px 16px rgba(15,23,42,.08)!important}.ppt-slide:nth-of-type(4) .sep-issues{border-top-color:#059669!important}.ppt-slide:nth-of-type(4) .sep-next{border-top-color:#7c3aed!important}.sep-num{display:flex;align-items:center;justify-content:center;flex:0 0 34px;height:34px;border-radius:50%;background:#dbeafe;color:#1d4ed8;font-size:15px;font-weight:900}.sep-issues .sep-num{background:#d1fae5;color:#047857}.sep-next .sep-num{background:#ede9fe;color:#6d28d9}.sep-card h4{font-size:19px!important;line-height:1.25!important;color:#0f172a!important;margin:0 0 8px!important;font-weight:900!important}.sep-card p{font-size:15.5px!important;line-height:1.48!important;color:#475569!important;margin:0!important}.sep-tags{display:flex!important;flex-wrap:wrap!important;gap:5px!important;margin:0 0 9px!important}.sep-tags span{font-size:13px!important;font-weight:800!important;color:#047857!important;background:#ecfdf5!important;border:1px solid #a7f3d0!important;border-radius:999px!important;padding:3px 7px!important}.sep-card ol{margin:0!important;padding-left:18px!important;color:#475569!important}.sep-card li{font-size:15px!important;line-height:1.5!important;margin-bottom:5px!important}.sep-card li b{color:#5b21b6!important}.sep-caution{font-size:14px!important;line-height:1.35!important;color:#9f1239!important;font-weight:800!important;padding:9px 13px!important;border:1px solid #fecdd3!important;border-radius:10px!important;background:#fff1f2!important}
 /* Mobile readability standard: title 34px, section title 24px, body 18px, supporting text 16px. */
 .ppt-slide [class~="text-xs"],.ppt-slide [class*="text-[11px]"],.ppt-slide [class*="text-[10px]"]{font-size:16px!important;line-height:1.46!important}.ppt-slide [class~="text-sm"]{font-size:18px!important;line-height:1.5!important}.ppt-slide [class~="text-base"]{font-size:20px!important}.ppt-slide [class~="text-lg"]{font-size:22px!important}.ppt-slide h3{font-size:34px!important;line-height:1.16!important}.ppt-slide h4{font-size:24px!important;line-height:1.24!important}.ppt-slide h5{font-size:20px!important}.ppt-slide th{font-size:18px!important}.ppt-slide td{font-size:17px!important;line-height:1.38!important}
 .ppt-slide:nth-of-type(2) .p2-intro{font-size:19px!important;line-height:1.48!important}.ppt-slide:nth-of-type(2) .p2-rules h4{font-size:23px!important}.ppt-slide:nth-of-type(2) .p2-rules p{font-size:18px!important;line-height:1.48!important}.ppt-slide:nth-of-type(2) .p2-rules a{font-size:16px!important}
 .ppt-slide:nth-of-type(3){justify-content:flex-start!important;gap:8px!important}.ppt-slide:nth-of-type(3)>div:last-child{margin-top:auto!important}.ppt-slide:nth-of-type(3) .problem-flow>div:nth-child(2) div,.ppt-slide:nth-of-type(3) .problem-flow>div:nth-child(4) div,.ppt-slide:nth-of-type(3) .problem-flow>div:nth-child(6) div{font-size:23px!important;line-height:1.18!important;font-weight:900!important}.ppt-slide:nth-of-type(3) .problem-flow small{font-size:16px!important;line-height:1.35!important}.ppt-slide:nth-of-type(3)>div:nth-child(4){padding:13px!important}.ppt-slide:nth-of-type(3)>div:nth-child(4) h4{font-size:23px!important}.ppt-slide:nth-of-type(3) .priority-list{margin:5px 0 0!important;padding-left:21px!important}.ppt-slide:nth-of-type(3) .priority-list li{font-size:17px!important;line-height:1.45!important;margin:3px 0!important}.ppt-slide:nth-of-type(3)>div:nth-child(5){flex:0 0 170px!important;height:170px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5)>div{display:flex!important;flex-direction:column!important;padding:12px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) h5{font-size:19px!important;line-height:1.16!important}.ppt-slide:nth-of-type(3) .pillar-list{display:grid!important;gap:3px!important;margin:5px 0!important;padding-left:20px!important;flex:0!important}.ppt-slide:nth-of-type(3) .pillar-list li{font-size:15px!important;line-height:1.18!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) .text-\\[11px\\]{display:none!important}
 .ppt-slide:nth-of-type(4) .sep-participation strong{font-size:21px!important}.ppt-slide:nth-of-type(4) .sep-participation span:last-child{font-size:16px!important}.ppt-slide:nth-of-type(4) .sep-card{padding:18px!important}.ppt-slide:nth-of-type(4) .sep-card h4{font-size:22px!important;line-height:1.18!important}.ppt-slide:nth-of-type(4) .sep-tags span{font-size:14.5px!important;padding:4px 8px!important}.sep-list,.sep-plan{list-style:none!important;margin:0!important;padding:0!important}.sep-list li,.sep-plan li{display:block!important;margin:0 0 10px!important;padding:0 0 9px!important;border-bottom:1px solid #e2e8f0!important}.sep-list li:last-child,.sep-plan li:last-child{margin-bottom:0!important;padding-bottom:0!important;border-bottom:0!important}.sep-list b,.sep-plan b{display:block!important;font-size:17px!important;line-height:1.25!important;color:#0f172a!important;margin-bottom:3px!important}.sep-list span,.sep-plan span{display:block!important;font-size:16px!important;line-height:1.38!important;color:#475569!important}.sep-next .sep-plan b{color:#5b21b6!important}.sep-caution{font-size:16px!important;line-height:1.38!important;padding:10px 14px!important}
 .ppt-slide:nth-of-type(5) table th,.ppt-slide:nth-of-type(5) table td{padding:14px 13px!important;font-size:17px!important}.ppt-slide:nth-of-type(5)>div:nth-child(3){padding:14px 17px!important}.cost-summary{display:grid!important;grid-template-columns:265px 1fr!important;gap:17px!important;align-items:center!important}.cost-hero{display:flex!important;flex-direction:column!important;gap:5px!important;padding-right:16px!important;border-right:2px solid #fcd34d!important}.cost-hero span{font-size:16px!important;font-weight:900!important;color:#92400e!important}.cost-hero strong{font-size:24px!important;line-height:1.12!important;color:#78350f!important}.cost-hero b{font-size:16px!important;line-height:1.3!important;color:#92400e!important}.cost-list{list-style:none!important;margin:0!important;padding:0!important;display:grid!important;gap:5px!important}.cost-list li{display:grid!important;grid-template-columns:120px 1fr!important;gap:8px!important;font-size:16px!important;line-height:1.34!important}.cost-list b{color:#92400e!important}.cost-list span{color:#334155!important}
 .ppt-slide:nth-of-type(7)>div:nth-child(2){flex:0 0 330px!important;height:330px!important;margin:6px 0 7px!important}.ppt-slide:nth-of-type(7)>div:nth-child(2)>div{padding:11px!important}.ppt-slide:nth-of-type(7)>div:nth-child(2) p{font-size:15px!important;line-height:1.3!important}.ppt-slide:nth-of-type(7)>div:nth-child(2) .space-y-3>div{padding:8px!important}.ppt-slide:nth-of-type(7)>div:nth-child(2) .space-y-3 strong{font-size:15.5px!important;line-height:1.2!important}.ppt-slide:nth-of-type(7)>div:nth-child(2) .space-y-3 span{font-size:14px!important;line-height:1.26!important}.jamsil-case-grid{gap:8px!important;margin:1px 0 4px!important}.jamsil-case{padding:7px 9px!important}.jamsil-case strong{font-size:15px!important;margin-bottom:2px!important}.jamsil-case p{font-size:12.5px!important;line-height:1.22!important;margin-bottom:2px!important}.case-timeline{font-size:12px!important;margin:0 0 2px!important}.jamsil-case a{font-size:10px!important}.strategy-box{padding:9px 13px!important}.strategy-box>div:first-child{margin-bottom:4px!important}.strategy-box>div:first-child strong{font-size:18px!important}.strategy-list{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:7px!important}.strategy-step{display:grid!important;grid-template-columns:29px 1fr!important;gap:6px!important;padding:6px!important;border-radius:10px!important;background:#334155!important}.strategy-step>span{display:flex!important;align-items:center!important;justify-content:center!important;width:28px!important;height:28px!important;border-radius:50%!important;background:#fbbf24!important;color:#1e293b!important;font-size:12px!important;font-weight:900!important}.strategy-step b{display:block!important;color:#fff!important;font-size:14px!important;line-height:1.14!important;margin-bottom:2px!important}.strategy-step p{margin:0!important;color:#dbeafe!important;font-size:12px!important;line-height:1.18!important}.strategy-note{margin:4px 0 0!important;padding-left:0!important;color:#fcd34d!important;font-size:12px!important;line-height:1.2!important}
 .ppt-slide:nth-of-type(3) .priority-logo{display:flex!important;flex:0 0 185px!important;align-items:center!important;justify-content:center!important;gap:7px!important;align-self:center!important;background:#fff!important;border-radius:10px!important;padding:8px 10px!important}.ppt-slide:nth-of-type(3) .priority-logo img{width:118px!important;height:30px!important;object-fit:contain!important}.ppt-slide:nth-of-type(3) .priority-logo span{font-size:12px!important;color:#64748b!important;font-weight:800!important;white-space:nowrap!important}.ppt-slide:nth-of-type(3)>div:nth-child(5){flex:0 0 145px!important;height:145px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) h5{font-size:18px!important}.ppt-slide:nth-of-type(3) .pillar-list li{font-size:14px!important;line-height:1.16!important}.ppt-slide:nth-of-type(4) .sep-list em,.ppt-slide:nth-of-type(4) .sep-plan em{display:block!important;color:#047857!important;font-size:13px!important;font-style:normal!important;font-weight:800!important;line-height:1.25!important;margin-top:3px!important}.ppt-slide:nth-of-type(4) .sep-next .sep-plan em{color:#6d28d9!important}.ppt-slide:nth-of-type(4) .sep-list li,.ppt-slide:nth-of-type(4) .sep-plan li{margin-bottom:7px!important;padding-bottom:7px!important}
 .ppt-slide:nth-of-type(6)>div:nth-child(2){flex:1 1 0!important;height:auto!important;min-height:0!important;gap:12px!important;margin:8px 0!important}.ppt-slide:nth-of-type(6)>div:nth-child(2)>div{padding:12px!important;min-height:0!important;overflow:hidden!important}.ppt-slide:nth-of-type(6)>div:nth-child(2) h4{font-size:20px!important;line-height:1.18!important;margin-bottom:8px!important}.ppt-slide:nth-of-type(6) .roadmap-list{gap:2px!important}.ppt-slide:nth-of-type(6) .roadmap-step{min-height:36px!important;padding:4px 8px!important}.ppt-slide:nth-of-type(6) .roadmap-step>div{font-size:15px!important;line-height:1.15!important}.ppt-slide:nth-of-type(6)>div:nth-child(2) strong{font-size:15px!important;line-height:1.15!important}.ppt-slide:nth-of-type(6)>div:nth-child(2) p{font-size:13px!important;line-height:1.2!important}.ppt-slide:nth-of-type(6)>div:nth-child(2)>div:last-child>div:last-child{font-size:12px!important;white-space:nowrap!important}.ppt-slide:nth-of-type(7)>div:first-child h3{font-size:30px!important;line-height:1.16!important}.ppt-slide:nth-of-type(7)>div:nth-child(2) .bg-amber-50{align-items:center!important}.ppt-slide:nth-of-type(7)>div:nth-child(2) .bg-amber-50>span:first-child{line-height:1.1!important;text-align:center!important}.ppt-slide:nth-of-type(8) table td{font-size:16px!important;padding:11px 14px!important}.ppt-slide:nth-of-type(8) table th{font-size:17px!important;padding:12px!important}.ppt-slide:nth-of-type(8)>div:first-child>div:first-child{max-width:86%!important}.ppt-slide:nth-of-type(8)>div:first-child h3{font-size:30px!important;line-height:1.16!important}
 .ppt-slide:nth-of-type(3)>div:nth-child(4){position:relative!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:16px 210px 16px 24px!important;margin-bottom:0!important}.ppt-slide:nth-of-type(3) .priority-copy{flex:0 1 780px!important;text-align:center!important}.ppt-slide:nth-of-type(3) .priority-copy>div{justify-content:center!important}.ppt-slide:nth-of-type(3) .priority-list{display:inline-grid!important;text-align:left!important;margin:11px auto 0!important}.ppt-slide:nth-of-type(3) .priority-logo{position:absolute!important;right:26px!important;top:50%!important;transform:translateY(-50%)!important;flex:0 0 auto!important;width:150px!important;height:48px!important;background:#fff!important;padding:7px 12px!important}.ppt-slide:nth-of-type(3) .priority-logo img{width:140px!important;height:34px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5){margin-top:0!important;padding-top:0!important}.ppt-slide:nth-of-type(3)>div:nth-child(5)>div{justify-content:flex-start!important;padding-top:10px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) h5{margin-top:0!important;margin-bottom:6px!important}
 .ppt-slide:nth-of-type(6)>div:nth-child(2) h4{font-size:25px!important;line-height:1.15!important}.ppt-slide:nth-of-type(6)>div:nth-child(2)>div:last-child .space-y-4{display:flex!important;flex:1!important;flex-direction:column!important;justify-content:space-between!important;gap:10px!important}.ppt-slide:nth-of-type(6)>div:nth-child(2)>div:last-child .space-y-4>div{display:flex!important;flex:1!important;flex-direction:column!important;justify-content:center!important;padding:15px!important}.ppt-slide:nth-of-type(6)>div:nth-child(2)>div:last-child strong{font-size:19px!important;line-height:1.18!important}.ppt-slide:nth-of-type(6)>div:nth-child(2)>div:last-child p{font-size:16px!important;line-height:1.3!important;margin-top:8px!important}
 .ppt-slide:nth-of-type(3)>div:nth-child(4) h4{font-size:29px!important;line-height:1.15!important}.ppt-slide:nth-of-type(3)>div:nth-child(4) .px-2\.5{font-size:17px!important;padding:6px 11px!important}.ppt-slide:nth-of-type(3)>div:nth-child(5){grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:12px!important;align-items:stretch!important}.ppt-slide:nth-of-type(3)>div:nth-child(5)>div{height:100%!important;box-sizing:border-box!important}.ppt-slide:nth-of-type(3)>div:nth-child(5) h5{font-size:20px!important;line-height:1.16!important}.ppt-slide:nth-of-type(3) .pillar-list li{font-size:15px!important;line-height:1.2!important}
 .ppt-slide:nth-of-type(4) .sep-card h4{font-size:21px!important}.ppt-slide:nth-of-type(4) .sep-list span,.ppt-slide:nth-of-type(4) .sep-plan span{font-size:14px!important;line-height:1.26!important}.ppt-slide:nth-of-type(4) .sep-list em,.ppt-slide:nth-of-type(4) .sep-plan em{font-size:12px!important;line-height:1.2!important}.ppt-slide:nth-of-type(4) .sep-list li,.ppt-slide:nth-of-type(4) .sep-plan li{margin-bottom:5px!important;padding-bottom:5px!important}
 .ppt-slide:nth-of-type(4) .sep-card{padding:15px!important}.ppt-slide:nth-of-type(4) .sep-card h4{font-size:22px!important;line-height:1.18!important}.ppt-slide:nth-of-type(4) .sep-list b,.ppt-slide:nth-of-type(4) .sep-plan b{font-size:16px!important}.ppt-slide:nth-of-type(4) .sep-list span,.ppt-slide:nth-of-type(4) .sep-plan span,.ppt-slide:nth-of-type(4) .sep-list em,.ppt-slide:nth-of-type(4) .sep-plan em{font-size:15px!important;line-height:1.26!important}.ppt-slide:nth-of-type(4) .sep-list em,.ppt-slide:nth-of-type(4) .sep-plan em{margin-top:2px!important}.ppt-slide:nth-of-type(4) .sep-list li,.ppt-slide:nth-of-type(4) .sep-plan li{margin-bottom:6px!important;padding-bottom:6px!important}
 .slide-survey .survey-grid,.slide-law .law-grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:14px!important;flex:1!important}.slide-survey .survey-card,.slide-law .law-card{display:flex!important;flex-direction:column!important;padding:17px!important;border-radius:16px!important;min-height:0!important}.slide-survey .survey-card{border:1px dashed #93c5fd!important;background:#f8fbff!important}.slide-survey .survey-card h4,.slide-law .law-card h4{font-size:20px!important;line-height:1.22!important;margin:8px 0!important}.slide-survey .survey-card p,.slide-law .law-card p{font-size:15px!important;line-height:1.38!important}.slide-survey .survey-slot,.slide-law .law-card a{margin-top:auto!important;padding-top:10px!important;font-size:13px!important}.slide-survey .survey-insight{margin-top:12px!important;padding:12px 16px!important;font-size:15px!important}.slide-law .law-card{border:1px solid #cbd5e1!important;border-top:4px solid #60a5fa!important;background:#fff!important}.slide-law .law-card:nth-child(2){border-top-color:#34d399!important}.slide-law .law-card:nth-child(3){border-top-color:#fbbf24!important}.slide-law .law-card:nth-child(4){border-top-color:#a78bfa!important}.slide-law .law-no{font-size:13px!important}.slide-law .law-lede{font-size:15px!important;margin:10px 0 12px!important}.slide-law .law-note{font-size:11px!important;line-height:1.35!important;margin-top:8px!important}
 table, .prevent-break{break-inside:avoid!important;page-break-inside:avoid!important} a{color:inherit;text-decoration:none} `;
 await page.addStyleTag({content:css+printCss});
 await page.pdf({path:releasePath,format:'A4',landscape:true,printBackground:true,preferCSSPageSize:true});await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});






